### ISSUE TITLE
DUT-OMRON Link is not working

### ISSUE THREAD

**Issue by songkq** [hkchengrex/CascadePSP#1]
Hi, @hkchengrex 
DUT-OMRON Link `(http://saliencydetection.net/duts/download/) ` is not working, I wonder if you could provide a `google drive` link for downloading the dataset? Many thanks. 
```
os.system("wget -P ../tmp_download_files http://saliencydetection.net/duts/download/DUTS-TR.zip")
os.system("wget -P ../tmp_download_files http://saliencydetection.net/duts/download/DUTS-TE.zip")
```

**Comment by a6o** [comment]
We believe that we are not allowed to redistribute the dataset. You might want to contact the authors of DUT-OMRON for the issue. As from our experience, the website is pretty unstable, but they come back after a day or two, so you might want to check the website later on. 

You might also consider training without DUT-OMRON, which does not affect the performance greatly.

**Comment by songkq** [comment]
Hi, @jjhoon713 
Thanks, I'll try without DUT-OMRON. 
And would you like to provide a `google drive` link for downloading the `pretrained model` instead of `OneDrive` link? OneDrive link can be rather slowly for me.

**Comment by hkchengrex** [comment]
We have added the Google Drive download option for the models and the dataset.

**Comment by songkq** [comment]
@hkchengrex  Many thanks.
