### ISSUE TITLE
download model error

### ISSUE THREAD

**Issue by MZener** [hkchengrex/CascadePSP#10]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=103nLN1JQCs2yASkna0HqfioYZO7MA_J9 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C46728F860>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有 正确答复或连接的主机没有反应，连接尝试失败。',))

**Comment by hkchengrex** [comment]
It works for me. Perhaps you can try the OneDrive link?

**Comment by hkchengrex** [comment]
Oh, do you mean the pip package? In that case, you can download the model manually and specify the model path in the init call.

**Comment by MZener** [comment]
Thanks for your reply. The problem is solved. @hkchengrex
