### ISSUE TITLE
issue of reproducing performance

### ISSUE THREAD

**Issue by Chenglin-Yang** [hkchengrex/CascadePSP#11]
Hi,

This work is very impressive!
I run this model using the released checkpoint, and the performance is very good. However when I tried to train a new model, I am not able to get the same performance. Could you please tell me which hyper parameters are used to get the released model's performance? 

I have tried 2 settings:
1. default setting in hyper_para.py.
2. batch_size=9, lr=3.0e-4, iterations=60000, steps=30000, 2gpus, as indicated in the paper.

Thank you very much!

**Comment by hkchengrex** [comment]
Using the default setting should yield the "new model" performance which is a bit better than the one used in the paper. We tried that before with this repo. Maybe you can show us the learning curve/output images?

**Comment by hkchengrex** [comment]
Closed due to inactivity.
