### ISSUE TITLE
How to use "squeezenet" as backend  to  train model??

### ISSUE THREAD

**Issue by wangjing60755** [hkchengrex/CascadePSP#12]
I can run with resnet，but too slow ,so how to use squeezenet???
I meet error:
RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[8, 6, 224, 224] to have 3 channels, but got 6 channels instead

**Comment by hkchengrex** [comment]
We modified the first conv in the network model to take 3 extra channels and initialized them with zeros. You need to change it in a similar way. For speed you can reduce it to a 2-level or even 1-level cascade -- the performance will drop but it will run much faster.

**Comment by wangjing60755** [comment]
can you put these codes? I can't modify

**Comment by hkchengrex** [comment]
You can find our modifications in models/psp/extractors.py.

**Comment by wangjing60755** [comment]
I find：
            if v1.shape != tar_v.shape:
                # Init the new segmentation channel with zeros
                c, _, w, h = v1.shape
                tar_v = torch.cat([
                    tar_v, 
                    torch.zeros((c,3,w,h)),
                ], 1)

but no use to me.
when I run train.py use "model = PSPNet(sizes=(1, 2, 3, 6), psp_size=2048, deep_features_size=1024, backend='squeezenet1_1')"
or " model = PSPNet(sizes=(1, 2, 3, 6), psp_size=2048, deep_features_size=1024, backend='resnet18') ", I meet error .I can,t know how to change the code to adapt！

**Comment by hkchengrex** [comment]
Only ResNet-50 is supported in this repo. You would have to include those extensions by yourself.
