### ISSUE TITLE
onedrive can't work

### ISSUE THREAD

**Issue by mikeswf** [hkchengrex/CascadePSP#13]
hi, there is something wrong with onedrive when we use it in china. So, can you upload something like model in google drive，thanks！
(作者你好呀，这个onedrive打开之后出现1s就消失了，不知道是不是在内地的原因，您方便的话可以上传到谷歌drive或者百度网盘什么的吗，谢谢啦)

**Comment by a6o** [comment]
For the models, they are uploaded in google drive. You can check them [here](https://github.com/hkchengrex/CascadePSP/blob/master/docs/models.md).

For other files, such as dataset, we will upload them in google drive and update the doc files.

**Comment by mikeswf** [comment]
thank you！

**Comment by hkchengrex** [comment]
Sorry for the delay. Most of the important bits (models/datasets) are already on Google Drive. Please contact us if you need others (e.g. precomputed results).
