### ISSUE TITLE
Long response time with the demo code

### ISSUE THREAD

**Issue by yanz20** [hkchengrex/CascadePSP#14]
Hi, I tried the following demo code in both my CPU only local machine and SageMaker but seems I have never got a response:
```python
import cv2
import time
import matplotlib.pyplot as plt
import segmentation_refinement as refine
image = cv2.imread('test/aeroplane.jpg')
mask = cv2.imread('test/aeroplane.png', cv2.IMREAD_GRAYSCALE)

# model_path can also be specified here
# This step takes some time to load the model
refiner = refine.Refiner(device='cpu') # device can also be 'cpu'

# Fast - Global step only.
# Smaller L -> Less memory usage; faster in fast mode.
output = refiner.refine(image, mask, fast=False, L=900) 

plt.imshow(output)
plt.show()
```
I had a successful case with using my 2070 GPU which response in 3s. Do you know what is taking that long for response in CPU-only machine? If I am using the pre-trained model only, is there a way to improve without losing accuracy? Thank you very much, it's a fantastic project!

**Comment by hkchengrex** [comment]
Speed was not a major consideration when we were developing this project -- I'm afraid that it wouldn't be particularly fast. To speed up inference without losing performance, you can use inference engines like TensorRT (GPU-only) or OpenVino. However, I am not sure what kind of speed-up you can get.

If you are willing to sacrifice performance, I suggest:
1. Downscaling the input by 2X. This speeds up inference ~4X. (Less performance loss)
2. Set `fast=True` in the `refine` call. (More performance loss)
