### ISSUE TITLE
How to make training model for paper?

### ISSUE THREAD

**Issue by github-luffy** [hkchengrex/CascadePSP#18]
Hi, Great work. After I read the paper, I have a question about model. Your code has just a Global Module. But I think the training process is shown in the picture below. Am I right？
![v2-b26e5f1b0b57afa70f01eebe61092881_1440w](https://user-images.githubusercontent.com/21214262/93191679-653eba00-f777-11ea-8fc8-5c054610a327.jpg)

**Comment by hkchengrex** [comment]
The code trains the RM (refinement module). The key to extending from low-resolution training images to high-resolution testing images is to use the **same** RM in both the global step and the local step. They are all shared-weight.

**Comment by github-luffy** [comment]
ok， Got it.
