### ISSUE TITLE
run demo,  there is a bug: Failed to establish a new connection: [Errno 101] Network is unreachable.

### ISSUE THREAD

**Issue by github-luffy** [hkchengrex/CascadePSP#19]
Downloading the model file into: /home/dell/.segmentation-refinement/model...
How to get model ?thanks

**Comment by hkchengrex** [comment]
Maybe your network cannot reach the model server. You can download it manually [here](https://github.com/hkchengrex/CascadePSP/blob/master/docs/models.md) and rename it to "model". Then you can pass the directory of the folder containing the model file to the "model_folder" argument.

Check the model loading code here: https://github.com/hkchengrex/CascadePSP/blob/master/segmentation-refinement/segmentation_refinement/main.py

**Comment by github-luffy** [comment]
The input image and mask can be of any size？or What is this demo used for?
image = cv2.imread('test/aeroplane.jpg')
mask = cv2.imread('test/aeroplane.png', cv2.IMREAD_GRAYSCALE)

**Comment by hkchengrex** [comment]
The input image/mask need to be of the same size. The demo images are located here: https://github.com/hkchengrex/CascadePSP/tree/master/segmentation-refinement/test.

**Comment by github-luffy** [comment]
> The input image/mask need to be of the same size. The demo images are located here: https://github.com/hkchengrex/CascadePSP/tree/master/segmentation-refinement/test.

Thanks for replying. I want to test my own images. It doesn't work? Must I train my own dataset?

**Comment by github-luffy** [comment]
Train my own dataset, a bug as above:
Traceback (most recent call last):
  File "train.py", line 124, in <module>
    train_integrator.finalize('train', total_iter)
  File "/data/YXQ/CascadePSP/util/log_integrator.py", line 50, in finalize
    k, v = hook(self.values)
  File "/data/YXQ/CascadePSP/util/metrics_compute.py", line 16, in <lambda>
    lambda x: get_new_iou_hook(x, '224'), lambda x: get_iou_gain(x, '224'),
  File "/data/YXQ/CascadePSP/util/metrics_compute.py", line 6, in get_new_iou_hook
    return 'iou/new_iou_%s'%size, values['iou/new_i_%s'%size]/values['iou/new_u_%s'%size]
ZeroDivisionError: float division by zero

The bug has been fixed, but will it affect training?

**Comment by hkchengrex** [comment]
> > The input image/mask need to be of the same size. The demo images are located here: https://github.com/hkchengrex/CascadePSP/tree/master/segmentation-refinement/test.
> 
> Thanks for replying. I want to test my own images. It doesn't work? Must I train my own dataset?

How does not it work? Did it crash or just perform badly?

**Comment by hkchengrex** [comment]
> Train my own dataset, a bug as above:
> Traceback (most recent call last):
> File "train.py", line 124, in
> train_integrator.finalize('train', total_iter)
> File "/data/YXQ/CascadePSP/util/log_integrator.py", line 50, in finalize
> k, v = hook(self.values)
> File "/data/YXQ/CascadePSP/util/metrics_compute.py", line 16, in
> lambda x: get_new_iou_hook(x, '224'), lambda x: get_iou_gain(x, '224'),
> File "/data/YXQ/CascadePSP/util/metrics_compute.py", line 6, in get_new_iou_hook
> return 'iou/new_iou_%s'%size, values['iou/new_i_%s'%size]/values['iou/new_u_%s'%size]
> ZeroDivisionError: float division by zero
> 
> The bug has been fixed, but will it affect training?

Probably because not even a single pixel has been predicted as foreground. Usually doesn't happen, but it's fine if it is just the early stage of training and the network adapt itself later on.

**Comment by github-luffy** [comment]
> > > The input image/mask need to be of the same size. The demo images are located here: https://github.com/hkchengrex/CascadePSP/tree/master/segmentation-refinement/test.
> > 
> > 
> > Thanks for replying. I want to test my own images. It doesn't work? Must I train my own dataset?
> 
> How does not it work? Did it crash or just perform badly?

perform badly.

**Comment by hkchengrex** [comment]
I don't know what your test images are so I cannot comment on that. Training on your own images may help.

**Comment by github-luffy** [comment]
run demo.py for my own image and mask , make sure image and mask right, but get output image as below. nothing?
![output](https://user-images.githubusercontent.com/21214262/93427859-1a48b200-f8f1-11ea-8088-b0d057a2ce84.png)

**Comment by hkchengrex** [comment]
Can I take a look at the input image/mask? The output image isn't that useful.

**Comment by github-luffy** [comment]
> Can I take a look at the input image/mask? The output image isn't that useful.

OK， giving image and mask.
![ACNE_00000039](https://user-images.githubusercontent.com/21214262/93428235-ab1f8d80-f8f1-11ea-82d2-c8efde3cd9fd.jpg)
![ACNE_00000039](https://user-images.githubusercontent.com/21214262/93428258-b672b900-f8f1-11ea-9fa9-bfd5c112ac56.png)

**Comment by github-luffy** [comment]
> Can I take a look at the input image/mask? The output image isn't that useful.
is mask 0/1 or 0/255?

**Comment by hkchengrex** [comment]
1. We assume the input mask to be a grayscale 0~255 image. You need to change the code for loading your mask to achieve that.
2. The face regions do not have clear boundaries (e.g. not an object, but semantic regions) which are indeed very different than our training images. Training on your own dataset (e.g. faces with these kinds of label) would definitely help.

**Comment by github-luffy** [comment]
> 1. We assume the input mask to be a grayscale 0~255 image. You need to change the code for loading your mask to achieve that.
> 2. The face regions do not have clear boundaries (e.g. not an object, but semantic regions) which are indeed very different than our training images. Training on your own dataset (e.g. faces with these kinds of label) would definitely help.

Thanks very much. Got it.
