### ISSUE TITLE
Does r_inter_tanh_s8 = torch.tanh(r_inter_s8) matter as for the intermediate segmentation?

### ISSUE THREAD

**Issue by songkq** [hkchengrex/CascadePSP#2]
Hi @hkchengrex ,

When the intermediate segmentations as inputs, i.e. `inter_s8 and inters_4`, are fed into the latter cascade level, the `tanh operation` is necessary to normalize inter-segmentation within range[-1, 1]? 

I wonder if it can be replaced with `sigmoid operation`? Does it have a significant effect on the performance?

**Comment by hkchengrex** [comment]
It should not have a significant effect. We simply normalize all segmentations to [-1, 1]. If you want to change it to a sigmoid, you need to un-do all our normalization in data preprocessing, etc.
