### ISSUE TITLE
What is the ground truth?

### ISSUE THREAD

**Issue by github-luffy** [hkchengrex/CascadePSP#20]
I have two classes. so i design the ground truth that has 0 for background and 1 for the other class. Am i right, or another way for ground truth?

**Comment by hkchengrex** [comment]
Our method is class-agnostic, so yes 0 for background 1 for everything else.

**Comment by hkchengrex** [comment]
Or you can do it twice, (background & class B = 0; class A = 1) and (background & class A = 0; class B = 1)

**Comment by github-luffy** [comment]
so when i have three and more classes, the ground truth is 0, 1, 2, 3......., OK?

**Comment by hkchengrex** [comment]
No. The current work only support binary segmentation (just 0/1) in training. You can use the one-vs-all method (used in our scene parsing extension) or change the network structure to support multi-class segmentation.

**Comment by github-luffy** [comment]
> No. The current work only support binary segmentation (just 0/1) in training. You can use the one-vs-all method (used in our scene parsing extension) or change the network structure to support multi-class segmentation.

yes, I found the network that has one dim for output. Thanks for your time.
