### ISSUE TITLE
ValueError: axes don't match array

### ISSUE THREAD

**Issue by revenkroz** [hkchengrex/CascadePSP#22]
If you run `test.py` from segmentation refinement package source you get an error `ValueError: axes don't match array` thrown at this line:
```
mask = self.seg_transform((mask>127).astype(np.uint8)*255).unsqueeze(0).to(self.device)
```

Probably important note: before running `python test.py` I've changed `cuda:0` to `cpu` at the line when you create a Refiner as I tested it on a machine without CUDA.

**Comment by hkchengrex** [comment]
Both 'cuda:0' and 'cpu' works on my PC. It might be a package version problem: can you double-check the shape of `mask`? It should be (2328, 3492) for the test mask.

**Comment by revenkroz** [comment]
Yeah, it looks fine:
```
image (2328, 3492, 3)
mask (2328, 3492)
```

I also tried to use this package (installed with 'pip install segmentation-refinement`) in U-2-NET to improve the mask shape and got the same error. 

I'll check packages version.

**Comment by hkchengrex** [comment]
Can you try changing
```python
output = refiner.refine(image, mask, fast=False, L=900) 
```
to
```python
output = refiner.refine(image, mask[:,:,None], fast=False, L=900) 
```
?

**Comment by revenkroz** [comment]
Yeah it works. Thanks!

So, I've checked package versions too. I was using an old torchvision. After I've updated the package, it works as good as you suggested with `mask[:,:,None]`.

**Comment by hkchengrex** [comment]
Yeah, your version was probably missing this one: https://github.com/pytorch/vision/pull/686.

BTW I would love to hear the result with U-2-Net!
