### ISSUE TITLE
Test effect of own data

### ISSUE THREAD

**Issue by github-luffy** [hkchengrex/CascadePSP#24]
My own data is about the semantic segmentation of two categories. This algorithm is only useful for object segmentation. It is not effective for region semantic segmentation？

**Comment by hkchengrex** [comment]
I would say that it should also work. There might not be enough training data in your task if I have to take a guess.

**Comment by github-luffy** [comment]
> I would say that it should also work. There might not be enough training data in your task if I have to take a guess.

1000 training data are really few,  I try to increase the data.
