### ISSUE TITLE
How to train on my own data?

### ISSUE THREAD

**Issue by richenyunqi** [hkchengrex/CascadePSP#26]
Thanks for your amazing work. It is very useful to me! However, how can I train a model on my own data? I browsed training.md but still did not grasp the key points. Do I have to download the training data you provided in training.md? Thanks for your help.

**Comment by hkchengrex** [comment]
You don't need to download those datasets if you are going to train the model on your own data.
You can look at [dataset/online_dataset.py](https://github.com/hkchengrex/CascadePSP/blob/master/dataset/online_dataset.py) to see how our data is prepared. If your own data has a different resolution other than ours (~300px * 500px), you might want to adjust the crop size.

Why do you want to train it on your own data though?

**Comment by richenyunqi** [comment]
Thanks for your reply. I think you can provide the details of how to train on personal data set in training.md. 
For your question, I have tested my own data on the model you provided. The accuracy of the boundary has been greatly improved, however, introducing other noise. There are mainly two problems. My data are human photos taken in a closed environment with lots of cameras. What I want to do is to classify the foreground and background of the human body. After I used your model, the black cameras appeared in the result, which did not appear in the initial segmentation result. On the other hand, part of the foreground of the human body was divided into the background. I don't know why, do you know the reason?
Anyway, your work is very helpful to me, thank you a lot!

**Comment by hkchengrex** [comment]
Maybe you can show some examples?
Anyway, if the images are dark/there are specific objects to remove, training on your own data is probably going to help.
We aren't really expecting others to train on their own data -- even if they do, there are engineering involved specific to the data that they use and a general tutorial would be difficult.

**Comment by richenyunqi** [comment]
I consider whether the problem is the label. I have a question. I want to classify the foreground and background, so what should the value of the label be? 0 and 1 or 0 and 255? If I use the 0 and 255, two problems talked about above appeared. If I use the 0 and 1, the result is a black image.

**Comment by hkchengrex** [comment]
It should be 0 and 255.

**Comment by richenyunqi** [comment]
So can the value of $L$ cause this result? I set the value of $L$ 600. Can you provide your email? I want to send you some of my data if you have time to help me to solve this problem. Thanks for your work and help again.

**Comment by hkchengrex** [comment]
It is not likely to be caused by L. If it's ok you can just post them here -- I might not be able to solve it since ultimately there might just be imperfections in the model/initial segments are too bad.

**Comment by richenyunqi** [comment]
![C11_IMG_6658_FRM_0080](https://user-images.githubusercontent.com/28208967/101868013-76049d80-3bb7-11eb-8ca0-db42bc6985a7.JPG)
![C11_IMG_6658_FRM_0080_INTER_NEAREST_binary](https://user-images.githubusercontent.com/28208967/101868021-7b61e800-3bb7-11eb-843d-ab39695e63ee.png)
![image](https://user-images.githubusercontent.com/28208967/101868197-c7149180-3bb7-11eb-99fd-3331149f8dd9.png)

From up to down, the RGB image, the initial segmentation image, and the resulting image processed with your model.

You can see, the red circle part of the resulting image is the camera which does not appear in the initial segmentation image, and the gray value of the red rectangle part of the resulting image is uneven and is not 255.

**Comment by hkchengrex** [comment]
Ah... I see. Thank you for the examples!
I would say that it is caused by the inherent limitation of cropping in our method. We tried our best to mitigate it but it seems that the problem still pops up sometimes.

Suggestions:
1. Increasing L might help but there is no guarantee
2. Training on your own data would definitely help
3. Train a different, more conservative model for the local step. This requires changing the core code. I might try this in my free time later.

**Comment by richenyunqi** [comment]
Thanks for your reply. I will try your method. Since the data needs to be kept confidential, I will delete the example. Thanks for your work and suggestions again.
