### ISSUE TITLE
Question about the transformation details

### ISSUE THREAD

**Issue by GOZGOXGOYGO** [hkchengrex/CascadePSP#29]
Hi @hkchengrex,
Actually, I still have some question about the transformation details. May I ask what is your purpose to normalize the 'seg' with mean 0.5 and std 0.5? Shouldn't 'seg' be a mask that only has value 0 and 1? And I am not very clear why you use torch.tanh in your network. Are there some advantages? Thank you so much!

**Comment by hkchengrex** [comment]
It's just standard normalization to bring the input to be in [-1, 1] -- kind of like how we normalize the images. It actually isn't that important but I did that anyway.

Tanh serves a similar purpose. It is not exactly the same as normalization, but the network (after training) does not care. Note that we still use sigmoid for outputting/computing losses.

**Comment by GOZGOXGOYGO** [comment]
Ah, I got it! Thanks you :) 

By the way, may I ask how to train the local step? As shown in the paper, in local step, we need input images include S11 and S41. However, if I use the prediction of global step as input, I can only get S11. So how can I get the S41 as input? Thanks a lot!

**Comment by hkchengrex** [comment]
You can also get S41 from the global step if you really wanted to. In the code, it should be `pred_56_2`.

**Comment by GOZGOXGOYGO** [comment]
Thanks, I will have a try.

**Comment by GOZGOXGOYGO** [comment]
Hi, 
I notice that the input image size of global step is W_G × H_G. But the input image size of local step is L×L. And as you mentioned, the refinement module is trained by images that are randomly cropped  into 224×224. Is it OK to use the same refinement module? And why does the global step don't need to take image crops? Thanks a lot.

**Comment by hkchengrex** [comment]
1. Yes. We have shown that.
2. Hmm why does it have to? W_G and L_G are already downsampled.

**Comment by GOZGOXGOYGO** [comment]
I am not sure if there is no need to control the network input for the same size. Sorry, I'm still a green hand. Thank you for your patient reply.

**Comment by hkchengrex** [comment]
The network is fully-convolutional so it does not require exact size input -- if that's what you are asking :smile:
