### ISSUE TITLE
Hi，can you illustrate gt.png,im.png,mask.png,seg.png,hre.png,what does these mean?

### ISSUE THREAD

**Issue by zhujiesuper** [hkchengrex/CascadePSP#3]

**Comment by hkchengrex** [comment]
gt - Ground truth
im - RGB image
seg - Segmentation input
mask - Our raw output
thre - Thresholded output

**Comment by zhujiesuper** [comment]
Thankyou,I know the gt and im！But if the seg represent input（seg）such like deeplab3+ output，and what does the raw output and thresholded output，I did not find in your paper.

**Comment by hkchengrex** [comment]
They are not in the paper because they are just minor implementation details. Raw output meaning the final output of our network, after the sigmoid operator. The thresholded output is just for visual inspection (thresholded at 0.5) and I don't think it is used in the evaluation.

**Comment by zhujiesuper** [comment]
thank for your reversion,i got it!
