### ISSUE TITLE
Questions about the function process_high_res_im

### ISSUE THREAD

**Issue by GOZGOXGOYGO** [hkchengrex/CascadePSP#30]
Hi,

may I ask why such kind of threshold can be used to define the not interesting area? And what if the object is relatively small? Thanks a lot.

```
# Skip when it is not an interesting crop anyway
seg_part_norm = (seg_224_part>0).float()
high_thres = 0.9
low_thres = 0.1
if (seg_part_norm.mean() > high_thres) or (seg_part_norm.mean() < low_thres):
        continue
grid_images = safe_forward(model, im_part, seg_224_part, seg_56_part)
grid_pred_224 = grid_images['pred_224'].to(aggre_device)
```

**Comment by hkchengrex** [comment]
It is to speed up processing.
If the object is really small it probably cannot be caught in the global step anyway. That being said you can still tune these thresholds for better results.

**Comment by GOZGOXGOYGO** [comment]
I'm not sure if here is a little mistake. It seems that the choice value should be of 0, 1, 2 or 3. Thanks.
```
def get_random_structure(size):
    choice = np.random.randint(4)

    if choice == 1:
        return cv2.getStructuringElement(cv2.MORPH_RECT, (size, size))
    elif choice == 2:
        return cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (size, size))
    elif choice == 3:
        return cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (size, size//2))
    elif choice == 4:
        return cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (size//2, size))
```

**Comment by hkchengrex** [comment]
Ah, it is a silly mistake. Thank you for pointing it out! :+1: 
Luckily it should not cause significant issues.
We will just leave it there and add a comment since our model is already trained with this bug.

**Comment by hkchengrex** [comment]
On second thought I will fix it and add a comment saying that the provided model is trained with the mentioned bug.
I have no idea how this silly bug can sneak into the code...

**Comment by GOZGOXGOYGO** [comment]
Thanks! It doesn't matter. This is undoubtedly an outstanding work. Fixing this little bug would theoretically yield better performance.
