### ISSUE TITLE
Some code branches in model and refinement are dead. Is it a mistake?

### ISSUE THREAD

**Issue by shkarupa-alex** [hkchengrex/CascadePSP#31]
I noticed that inter_s4 here https://github.com/hkchengrex/CascadePSP/blob/master/segmentation-refinement/segmentation_refinement/eval_helper.py#L13 and corresponding one here https://github.com/hkchengrex/CascadePSP/blob/master/models/psp/pspnet.py#L92 are never used in evaluation.

Are they redundant? Or it is a mistake? Or it was used only for some earlier experiments?

**Comment by hkchengrex** [comment]
Yes, they were used for some earlier experiments only.
