### ISSUE TITLE
Got quite strange result with chessboard-like on it!

### ISSUE THREAD

**Issue by CeciliaPYY** [hkchengrex/CascadePSP#33]
```
image = cv2.imread('/mnt/work/yuyanpeng/code/personal/PaddleSeg/deploy/python/dataset/360/doll/image/00_26.jpg')
mask = cv2.imread(
    '/mnt/work/yuyanpeng/code/personal/PaddleSeg/deploy/python/dataset/360/doll/mask/00_26.jpg', cv2.IMREAD_GRAYSCALE)
    
# model_path can also be specified here
# This step takes some time to load the model
refiner = refine.Refiner(device='cuda:0', model_folder="../downloaded_model") # device can also be 'cpu'

# Fast - Global step only.
# Smaller L -> Less memory usage; faster in fast mode.
output = refiner.refine(image, mask, fast=False, L=800) 

plt.imshow(output)
plt.show()
```

Following is the result.
![image](https://user-images.githubusercontent.com/30582437/103331965-2d981b80-4aa3-11eb-83c2-1c4108fd2c53.png)

**Comment by hkchengrex** [comment]
Can you post the raw image/mask here for reference?

**Comment by CeciliaPYY** [comment]
Yes, definitely!
![00_26_img](https://user-images.githubusercontent.com/30582437/103495154-bb458380-4e74-11eb-9f36-05f887e305ca.jpg)
![00_26_mask](https://user-images.githubusercontent.com/30582437/103495158-bf71a100-4e74-11eb-8f25-1d95b74a6b24.jpg)

**Comment by hkchengrex** [comment]
Thanks!

I just ran the algorithm using [test.py](https://github.com/hkchengrex/CascadePSP/blob/master/segmentation-refinement/test.py) and it works fine (see below). Maybe you can let it download the model again?

Raw output, the nose region is not ideal but it still passes the 0.5 threshold:
![Figure_1](https://user-images.githubusercontent.com/7107196/103499824-690c5e80-4e84-11eb-96c6-dd795a1764d9.png)

After thresholding:
![Figure_2](https://user-images.githubusercontent.com/7107196/103499871-8d683b00-4e84-11eb-8552-ec87d55586f8.png)

**Comment by CeciliaPYY** [comment]
Thanks, I'll try it again and let you know if it works out fine~
