### ISSUE TITLE
Something about ResNet50

### ISSUE THREAD

**Issue by GOZGOXGOYGO** [hkchengrex/CascadePSP#34]
Hi,

may I ask what is the purpose to use dilation in your code? and how did you add the zero-initialized channels to the first conv. I cannot find it.

Thank you.

**Comment by hkchengrex** [comment]
1. We reduce the stride to increase the output resolution. This results in a decrease in receptive field which is mitigated by dilated convolution. This is a standard practice in segmentation networks.
2. https://github.com/hkchengrex/CascadePSP/blob/3e9a79b7454c1fe2f2484aa517ac0161517ecc21/models/psp/extractors.py#L28

**Comment by GOZGOXGOYGO** [comment]
Thanks. May I ask the reason why the padding parameter in `step_size = stride - padding * 2` is set as 16?

**Comment by hkchengrex** [comment]
It is empirically set. With a larger padding it should also work; with a smaller padding you might run into boundary artifacts.
