### ISSUE TITLE
Purpose of input padding

### ISSUE THREAD

**Issue by shkarupa-alex** [hkchengrex/CascadePSP#35]
Could you please tell what is the purpose of this padding https://github.com/hkchengrex/CascadePSP/blob/master/segmentation-refinement/segmentation_refinement/eval_helper.py#L18 ?

As far as i know convolutions are invariant to input size

**Comment by hkchengrex** [comment]
The input size has to an integer multiple of 8 or else it will clog up the upsampling process.
For example, if we start with an image with side length 223, the dimension during encoding will be like:
223 -> 111 (strided convolution)
and in the upsampling process:
111 -> 222 (bilinear upsampling) which does not match 223.

This is an example with stride 2. Our model has stride 8.
