### ISSUE TITLE
CascadePSP performed bad on small object

### ISSUE THREAD

**Issue by CeciliaPYY** [hkchengrex/CascadePSP#36]
It seems cascadePSP's performance is not good enough when dealing with small objects, the following is the before and after.
![image](https://user-images.githubusercontent.com/30582437/106551549-76cf0580-6550-11eb-8ceb-3dfb36862c16.png)
![image](https://user-images.githubusercontent.com/30582437/106551553-7a628c80-6550-11eb-90d5-ab5dd989a4d4.png)

**Comment by hkchengrex** [comment]
That's correct. We assume that the target object occupies a significant portion of the input image. If you are dealing with small objects it is probably better to crop the image (with a dilated minimum bounding box) first. We did similar things in the scene parsing part of our paper.

**Comment by CeciliaPYY** [comment]
Thanks for reply, I'll give it a try~~
