### ISSUE TITLE
The expanded size of the tensor (654) must match the existing size (675) at non-singleton dimension 2

### ISSUE THREAD

**Issue by feiyun1265** [hkchengrex/CascadePSP#37]
p_im[:,:,0:ph,0:pw] = im
RuntimeError: The expanded size of the tensor (654) must match the existing size (675) at non-singleton dimension 2.  Target sizes: [1, 3, 654, 900].  Tensor sizes: [3, 675, 900].

input size: 3 * 640 * 480
mask size; 176 * 128

Can you help me with the problem, thanks

**Comment by hkchengrex** [comment]
The mask size would need to match the image size. You can use bilinear/nearest upsampling to achieve that.

**Comment by feiyun1265** [comment]
> The mask size would need to match the image size. You can use bilinear/nearest upsampling to achieve that.

I see. thank  u very much!
