### ISSUE TITLE
Boundary_accuracy

### ISSUE THREAD

**Issue by antosum** [hkchengrex/CascadePSP#38]
Hello,
I have a questions about the boundary accuracy metric implementation.
If I understand well you take the subset of the segmentation maps around the GT boundaries for various radiis.
But why using the accuracy metric since it won't go lower than 0.5 even if the model predicts nothing? That seems misleading to address boundary quality.

I suggest processing the dilated boundaries of GTs and PREDs and computing IoU or Dice on those for each radius.
This will range from 0. to 1. for no overlap to perfect overlap. 

I think this is the way it's computed in the Edge Detection community, except they take F1 score.

**Comment by hkchengrex** [comment]
We used this simple metric mainly for comparison with other methods and frankly did not think too much about it. Even if we use IoU, the metric would not go below 0.5 if the model predicts everything (which is not that different from a segmentation point of view). Regardless, using a single number computed at a pixel-level to represent boundary quality without perceptual consideration is likely going to be misleading. All the compared methods, however, stem from CNNs, have similar prediction pattern, and therefore we believe pixel accuracy still represent the *relative* quality faithfully.

You are of course welcomed to try other metrics, and we will be interested in the results. :beers:
