### ISSUE TITLE
testing segmentation

### ISSUE THREAD

**Issue by cchenzhou** [hkchengrex/CascadePSP#39]
sorry, I having training this model by using VOC2012 dataset and I want to test my model on val dataset.
But I don't know why test directory should include three types images, that is _im.jpg, _seg.png and _gt.png.
I have known that ground truth images and RGB images, but what is input segmentation images?
How to produce it?

**Comment by hkchengrex** [comment]
Our model is defined to be a *segmentation refinement* network -- it takes an input segmentation and refines it. We usually feed it with initial segmentations generated by other methods.
