### ISSUE TITLE
hello,i train your data,but when i want to test the model,AttributeError: 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.

### ISSUE THREAD

**Issue by zhujiesuper** [hkchengrex/CascadePSP#4]

**Comment by hkchengrex** [comment]
What command did you use?

**Comment by zhujiesuper** [comment]
python eval.py --dataset CascadePSP-master/testset_directory  --CascadePSP-master/weights/3_2020-05-17_12:15:38/model_45705 --output CascadePSP-master/testset_directory       --------the model trained by your method completely

**Comment by hkchengrex** [comment]
The "--model" phrase is missing before the model file.

**Comment by zhujiesuper** [comment]
Thank YOU! I change this,but A new broken,0 images found,,,my code is python eval.py --dataset /home/zj/PycharmProjects/CascadePSP-master/CascadePSP-master/testset_directory  --model /home/zj/PycharmProjects/CascadePSP-master/CascadePSP-master/weights/3_2020-05-17_12:15:38/model_45000 --output /home/zj/PycharmProjects/CascadePSP-master/CascadePSP-master/output_directory
and the testset_directory I put xxxx_gt.png,xxxx_im.png,xxx_seg.png which come from the BIG dataset

**Comment by hkchengrex** [comment]
The image files should be in .jpg. If your images are in .png you can modify the dataset class to take png pretty easily.

**Comment by zhujiesuper** [comment]
ThankYou！I solve this by change --dataset to --dir ,and png is ok  ,jpg need modify! see the result,it is an awesome job!

**Comment by zhujiesuper** [comment]
but why in eval.py i need to put the _gt.png in test,did the _gt.png affect the result?

**Comment by hkchengrex** [comment]
Thanks for pointing that out! We actually had a typo in the document which we will now fix. The _gt files do not affect the results. They are just copied to the output folder for future evaluation.

**Comment by zhujiesuper** [comment]
Nothing,Nothing,This job is very awesome!

**Comment by hkchengrex** [comment]
Thanks! 😄
