### ISSUE TITLE
About sample rate in boundary_modification.py

### ISSUE THREAD

**Issue by peterlv666** [hkchengrex/CascadePSP#42]
Thanks for your work. I try to understand why you choose small value as sample rate,  you choose the contour that the shape is more than ten to modify the contour. I thought big sample rate can help contain more information in a specify contour. So can you explain the reason why you choose 0.1 as the sample rate?

**Comment by hkchengrex** [comment]
@a6o

**Comment by a6o** [comment]
No. We don't want to contain more information. 

boundary_modification is only used to generate training data. When we feed ground-truth segmentation to boundary_modification.py, we want it to resemble inaccurate segmentation as if it is given from some fully-trained model. 
We are trying to destroy/modify information from ground truth to resemble inaccurate segmentation of a trained model.

The main purpose of boundary_modification is to remove fine details (e.g., tails, limbs, and other outer/inner appendages). 
With low sample_rate, output segmentation map overlaps well with the original segmentation, while omitting thin appendages.

**Comment by peterlv666** [comment]
@a6o  Thanks for your reply  in time.  Now,  i can understand that.
