### ISSUE TITLE
how to get the name_seg.png when testing on semantic segmentation ?

### ISSUE THREAD

**Issue by peterlv666** [hkchengrex/CascadePSP#43]
Sorry to bother you agin.  
1.When i  testing on semantic segmentation use the BIG datasets you provided, i found that datasets haven't the name_seg.png picture as you described in the readme. I want to know how to get that style of the seg.png picture.
2.Your paper mentioned the crop process in Local step,  in your code i don't find that process. Whether this process output the seg.png picture ?  
![image](https://user-images.githubusercontent.com/75125316/117829313-3ac0e480-b2a5-11eb-885b-3766e9d2a371.png)
Thanks for your time and kindness.

**Comment by hkchengrex** [comment]
1. This code performs *segmentation refinement*, so we need to start with a segmentation and refine it. That segmentation is the `_seg.png` file. You can obtain those using other semantic segmentation methods (e.g., deeplab). We do provide some precomputed `_seg.png` in the download section.

2. See here: https://github.com/hkchengrex/CascadePSP/blob/aef152ece2e7e1ace8ff0d99713b17f8dd55e650/eval_helper.py#L71
