### ISSUE TITLE
Cannot execute the test refinement

### ISSUE THREAD

**Issue by SchernHe** [hkchengrex/CascadePSP#45]
Hey guys, 

first of all, thanks for your great work. 

I just tried to reproduce the test example (aeroplane), but received the following error:

```
     66             image = self.im_transform(image).unsqueeze(0).to(self.device)
---> 67             mask = self.seg_transform((mask>127).astype(np.uint8)*255).unsqueeze(0).to(self.device)
     68             if len(mask.shape) < 4:
     69                 mask = mask.unsqueeze(0)

~/Documents/Programming/VirtualEnvironments/python3_venv/lib/python3.7/site-packages/torchvision/transforms/transforms.py in __call__(self, img)
     47     def __call__(self, img):
     48         for t in self.transforms:
---> 49             img = t(img)
     50         return img
     51 

~/Documents/Programming/VirtualEnvironments/python3_venv/lib/python3.7/site-packages/torchvision/transforms/transforms.py in __call__(self, pic)
     74             Tensor: Converted image.
     75         """
---> 76         return F.to_tensor(pic)
     77 
     78     def __repr__(self):

~/Documents/Programming/VirtualEnvironments/python3_venv/lib/python3.7/site-packages/torchvision/transforms/functional.py in to_tensor(pic)
     46     if isinstance(pic, np.ndarray):
     47         # handle numpy array
---> 48         img = torch.from_numpy(pic.transpose((2, 0, 1)))
     49         # backward compatibility
     50         if isinstance(img, torch.ByteTensor):

ValueError: axes don't match array
```

I run the following:

```
refiner = refine.Refiner(device='cpu')

image = cv2.imread('cascade/aeroplane.jpg')
mask = cv2.imread('cascade/aeroplane.png', cv2.IMREAD_GRAYSCALE)

output = refiner.refine(image, mask, fast=True, L=900) 
```

---- 

Tried it with both `torch-1.0.0 torchvision-0.2.1` and the newest versions, but always get the same error. Is this a known issue?

**Comment by hkchengrex** [comment]
Are you using the provided images? Can you show `image.shape` and `mask.shape`?
I just tested with the latest torch and torchvision and it still works.

**Comment by SchernHe** [comment]
Thanks for the fast response. 

Yes, I just use the provided images.

```
image.shape
(2328, 3492, 3)

mask.shape
(2328, 3492)
```

**Comment by hkchengrex** [comment]
They are correct.
Can you update torchvision and try again? I just noticed that `0.2.1` is very old.

**Comment by SchernHe** [comment]
Can you maybe tell me the exact versions that you are using, for both torch and torchvision?

**Comment by hkchengrex** [comment]
Back then I think it was torch `1.0` and torchvision `0.4`
Currently, I am using torch `1.8.1` and torchvision `0.9.1`

I am fairly confident that it will work for any versions in between.

**Comment by SchernHe** [comment]
I now get the following warning and the command does not execute (its running for approx. 20min now).

```
.../lib/python3.7/site-packages/torch/nn/functional.py:3503: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details. 
  "The default behavior for interpolate/upsample with float scale_factor changed "

```

**Comment by hkchengrex** [comment]
You can ignore that warning.
On my machine it took around a minute (on CPU, fast=True, L=900) to complete. Is your CPU running? Or maybe swap is engaged? You can try lowering L (to maybe 100) just to debug.

**Comment by SchernHe** [comment]
Thanks for your help. My hardware was indeed just to slow and it worked with L=100.
Switched to a remote GPU and it works like a charm. I will now go on and test it with some custom data. Thanks again!
