### ISSUE TITLE
How to generate Binary Masks from labelled dataset?

### ISSUE THREAD

**Issue by shubham12tomar** [hkchengrex/CascadePSP#47]
Sir,

As you reannotate the PASCAL VOC 2012 dataset, can you please tell me how can we generate binary masks from my dataset labelled using LabelMe Image Annotator in python (it generates JSON files), so that I can train this model on my custom dataset. I am doing Instance segmentation and labelled the data according to this.

Please provide that code.

Thanks

**Comment by hkchengrex** [comment]
We did not use LabelMe or JSON annotations. There should be some open-sourced online routines to convert those formats to numpy arrays and you can just convert them to binary format.
