### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by zhujiesuper** [hkchengrex/CascadePSP#5]
hello ,when I want to run 
```python eval_post.py --dir /home/zj/PycharmProjects/CascadePSP-master/CascadePSP-master/output_directory --output /home/zj/PycharmProjects/CascadePSP-master/CascadePSP-master/output_temp_result```
,occur a broke : 

```
File "eval_post.py", line 64, in <module>
    this_class = int(re.search(r'\d+', gt_name[::-1]).group()[::-1]) - 1
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by a6o** [comment]
Could you tell us whats inside /home/zj/PycharmProjects/CascadePSP-master/CascadePSP-master/output_directory

**Comment by zhujiesuper** [comment]
okok,it is from eval.py 's output  contain  _gt.png,_im.png,_mask.png,_seg.png

**Comment by zhujiesuper** [comment]
only one picture,has 4 this

**Comment by zhujiesuper** [comment]
Thankyou! I solve this by change the file name
