### ISSUE TITLE
Dataset problem

### ISSUE THREAD

**Issue by baomimianbobo** [hkchengrex/CascadePSP#50]
Hello, author! My dataset is segmented using labelme, generates a JSON file, and a picture is segmented into classes. Can you train this network? Can there be multiple categories of segmentation results for a single image? If not, how can I make changes to my annotated image?

**Comment by hkchengrex** [comment]
1. You would need to write your own JSON dataloader.
2. We use a single segment per image for training (if you have multiple, one idea is to pick a random segment). In test-time, you can run refinement for different segments independently and fuse the results together.

**Comment by baomimianbobo** [comment]
Thank you very much for your reply. I have two more questions:
1、My original image is a very large and messy image of weeds, can not be directly on the original image annotation, Therefore, when labeling the image, it is necessary to cut the original image into hundreds of small images for labeling, The training is also carried out with the image of small map and marked map, and the test is carried out with the original large map. But I see that your experiment is labeled, trained, and tested directly on the original graph, so does your model apply to my kind of data set?
2、When I tested eval.py with your dataset, the following error occurred：
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Does the blogger know what’s going on?
Thank you very much!!!

**Comment by hkchengrex** [comment]
1. Can I see some examples? Granted our network is not suitable for images that require high-resolution context. We train on low-res images and predict on both low-res and high-res images.
2. There should not be multiple processes calling `eval.py`. What was your command?
