### ISSUE TITLE
Perturbed labels

### ISSUE THREAD

**Issue by cloudyliy** [hkchengrex/CascadePSP#51]
Dear author:
Is there any data perturbation code in this package? I didn't find it. Can you send me a copy? Thank you very much!

**Comment by hkchengrex** [comment]
Here: https://github.com/hkchengrex/CascadePSP/blob/a7f7836275d6fa914d320d0bfbe6c19cfb6c2f8d/util/boundary_modification.py#L12

**Comment by cloudyliy** [comment]
Thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rex ***@***.***&gt;; 
发送时间: 2021年9月18日(星期六) 上午10:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hkchengrex/CascadePSP] Perturbed labels (#51)





 
Here: https://github.com/hkchengrex/CascadePSP/blob/a7f7836275d6fa914d320d0bfbe6c19cfb6c2f8d/util/boundary_modification.py#L12
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
