### ISSUE TITLE
Small question about mean boundary accuracy

### ISSUE THREAD

**Issue by 95maddycode** [hkchengrex/CascadePSP#52]
Hi, 

To compute the mean boundary accuracy, the compute_boundary_acc function is called, with the parameters gt, seg and mask.

I understand that gt is the ground truth mask. However, what are seg and mask? Is there any difference between the two? 

Also, why is there a difference calculated in old mBA and new mBA in CascadePSP/eval_post.py ?

Thanks in advance for answering my questions,

Kind regards

**Comment by hkchengrex** [comment]
`seg` is the "original" mask that is the input to our algorithm.
`mask` is the output of our algorithm.
So old mBA is the mBA of the input mask, and new mBA is the mBA of the output mask.
