### ISSUE TITLE
Error while running demo code!!

### ISSUE THREAD

**Issue by Guttappa1238** [hkchengrex/CascadePSP#54]
Hi,

I installed pip package using this `pip install segmentation-refinement` and when i run demo code 

```
import cv2
import time
import matplotlib.pyplot as plt
import segmentation_refinement as refine
image = cv2.imread('test/aeroplane.jpg')
mask = cv2.imread('test/aeroplane.png', cv2.IMREAD_GRAYSCALE)

# model_path can also be specified here
# This step takes some time to load the model
refiner = refine.Refiner(device='cuda:0') # device can also be 'cpu'

# Fast - Global step only.
# Smaller L -> Less memory usage; faster in fast mode.
output = refiner.refine(image, mask, fast=False, L=900) 

# this line to save output
cv2.imwrite('output.png', output)

plt.imshow(output)
plt.show()
```
I got this error 
```
magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.
```
Please help me!!

**Comment by hkchengrex** [comment]
Model downloading probably failed. You can download it manually and point the path to it. See https://github.com/hkchengrex/CascadePSP/blob/3d1a645c0a65725d237756c796a25cfaaac667d0/segmentation-refinement/segmentation_refinement/main.py#L13

**Comment by Guttappa1238** [comment]
@hkchengrex  thank you, because of model not downloaded successfully i got that error but my question is that why its failed to download you know any reason?

**Comment by hkchengrex** [comment]
There can be many reasons. Network failure, canceling mid-download, or just google drive not collaborating. The code is in no way robust to these situations.

**Comment by amaanmakhani** [comment]
What arguments did you pass refine? I passed my path to my downloaded model and the error still occurred for me.
