### ISSUE TITLE
How to change epoch?

### ISSUE THREAD

**Issue by idazhuang** [hkchengrex/CascadePSP#55]
I have a question, from now on I don't know how to change epoch. Would you please tell me?

**Comment by hkchengrex** [comment]
You can change the number of training iterations in util/hyper_para.py

**Comment by idazhuang** [comment]
> You can change the number of training iterations in util/hyper_para.py

Thank you . I solved the problem last night. But I have a new question, the weight file don't have suffix name，right?

**Comment by hkchengrex** [comment]
I don't understand your question...
