### ISSUE TITLE
Segmentation Refinement Runtime Error

### ISSUE THREAD

**Issue by amaanmakhani** [hkchengrex/CascadePSP#56]
I am trying to run the segmentation refinement and get the following error. I followed the install steps using pip. Here is what happens when I clone the repo and run test.py. I am using Windows 11 but have also tried running the code using WSL and the result was the same.

`C:\Users\amaanmakhani\Desktop\CascadePSP\segmentation-refinement>python test.py
Traceback (most recent call last):
  File "C:\Users\amaanmakhani\Desktop\CascadePSP\segmentation-refinement\test.py", line 12, in <module>
    refiner = refine.Refiner(device='cuda:0') # device can also be 'cpu'
  File "C:\Users\amaanmakhani\Desktop\CascadePSP\segmentation-refinement\segmentation_refinement\main.py", line 32, in __init__
    model_dict = torch.load(model_path, map_location={'cuda:0': device})
  File "C:\Users\amaanmakhani\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\amaanmakhani\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.`

I would appreciate anyone's help.

-Amaan

**Comment by hkchengrex** [comment]
Can you delete the model file and download it again? Seems like a file corruption problem.

**Comment by amaanmakhani** [comment]
It was. The download from Google Drive seems to be corrupt. One drive worked.

**Comment by ttsesm** [comment]
I am getting a similar error. I've install the package with `pip` in my current virtual env. @hkchengrex I guess you are talking about these models https://github.com/hkchengrex/CascadePSP/blob/master/docs/models.md, right?

I do not understand though, once I download the model file, where should I put it within my project folder structure? Is it necessary to clone the whole repo once I install the package with `pip`?

**Comment by hkchengrex** [comment]
You can put it anywhere in a folder, and pass the path of the folder to the `model_folder` argument of Refiner.
Seems like downloading from google drive is causing more problems than it should. I will see if I can fix it.

**Comment by TNNSLAB** [comment]
I'm having the same problem :( how do you guys solved this ?

**Comment by ttsesm** [comment]
@hkchengrex thanks ;-)

@schwarzwals just download one of the models from the link that I noted in my previous post. Rename it to `model` instead of `new_model` (that was needed at least for the newer model from onedrive) Thereafter, just change the following line in `test.py` from:
```
refiner = refine.Refiner(device='cuda:0)
```
to
```
refiner = refine.Refiner(device='cuda:0', model_folder='/folder/path/to/where/the/model/file/is/located/')
```
and it should work without issues now.

**Comment by TNNSLAB** [comment]
@ttsesm i'm doing this on a Mac OS machine...still no luck...
i installed it also using pip...
do i need to download the repository or...
strange...
thank you

**Comment by ttsesm** [comment]
Hhmm, interesting. On my linux machine it works without issues, though it shouldn't do any difference in yours as well. Unfortunately, I do not have a mac machine to test. I've also installed the package through pip in my venv, and not I did not have to download anything else from the repository apart from the model.

**Comment by hkchengrex** [comment]
We have updated the package to check for errors and replaced g-drive with GitHub. This should be solved now. Thanks!

**Comment by epicgzs1112** [comment]
it's not work! once i put run button! the downloading file  overwrite it .

**Comment by epicgzs1112** [comment]
is fucking  dieth loop
