### ISSUE TITLE
Train the Net

### ISSUE THREAD

**Issue by wanghr-git** [hkchengrex/CascadePSP#57]
How much memory is needed to train this network?

**Comment by wanghr-git** [comment]
> How much memory is needed to train this network?

for GPU

**Comment by wanghr-git** [comment]
does all the RM share the weights?(I'm new to this, sorry to bother you)

**Comment by hkchengrex** [comment]
We used two 11G 1080Ti for training.
They all share weights. See the paper for details.

**Comment by wanghr-git** [comment]
> We used two 11G 1080Ti for training. They all share weights. See the paper for details.

thanks!
