### ISSUE TITLE
how to solve this problem?

### ISSUE THREAD

**Issue by Burning-burning** [hkchengrex/CascadePSP#59]
requests.exceptions.SSLError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=103nLN1JQCs2yASkna0HqfioYZO7MA_J9 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))

**Comment by a6o** [comment]
Seems like the error is coming from downloading the model weights. Try to download them manually.

**Comment by a6o** [comment]
Seems like the model weight is not downloaded. 
could be duplicate of #53

**Comment by hkchengrex** [comment]
We have updated the package to check for errors and replaced g-drive with GitHub. This should be solved now. Thanks!
