### ISSUE TITLE
hello,when i want to use SceneParsing how  i  process individual components?

### ISSUE THREAD

**Issue by zhujiesuper** [hkchengrex/CascadePSP#6]

**Comment by hkchengrex** [comment]
It can be done by appending the `--ade` flag to eval.py. See [here](https://github.com/hkchengrex/CascadePSP/blob/master/docs/testing_scene_parsing.md).

**Comment by zhujiesuper** [comment]
I add --ade but only have one class mask ，the other class i can not find

**Comment by zhujiesuper** [comment]
if I use the wrong data ，I use ADE_EncNet_SS_ours for eval.py

**Comment by hkchengrex** [comment]
You need to use the "Pre-processed 'split' input" [here](https://github.com/hkchengrex/CascadePSP/blob/master/docs/dataset.md). We pre-process the scene parsing data into segments for easier handling.

**Comment by zhujiesuper** [comment]
okok，the eval.py run correctly,but the eval_post_ade broken:    new_class_i[c] += new_i
IndexError: list index out of range
can you tell me such like --mask_dir XXX ,---seg_dir YYY,,,,,the XXX,andYYY and ZZZ I do not konw the data is what in detail ,can you support this to me?

**Comment by hkchengrex** [comment]
They are mentioned [here](https://github.com/hkchengrex/CascadePSP/blob/master/docs/testing_scene_parsing.md).

**Comment by zhujiesuper** [comment]
sorry ，i see this,but i do not solve becouse i do not not what data to put the correct local.  can you give me a clarity note.   such like --mask_dir XXX ,---seg_dir YYY,,,,,the XXX,andYYY and ZZZ,and XXX use what data from the onedrive,like ADE_PSPNet_MS_ours

**Comment by hkchengrex** [comment]
mask_dir -- The output folder you generated with eval.py
seg_dir -- Download from the "segmentation inputs" column
gt_dir -- The "annotations" folder downloaded from the official ADE20K website
split_dir -- The input folder you used in eval.py

**Comment by zhujiesuper** [comment]
thank you! I run this well ,but the "segmentation inputs" column whether is the original pspnet output?
and Break down the scene parse into individual components using the method described in the paper,,,,,do this have code which not provide?

**Comment by hkchengrex** [comment]
The code is in the repo, in scripts/ade20K. They are not documented and quite messy though.

**Comment by zhujiesuper** [comment]
okok, the "segmentation inputs" column whether is the original pspnet output?

**Comment by zhujiesuper** [comment]
and can you provide scripts/ade20K run step,which i run first and next?

**Comment by hkchengrex** [comment]
1. If you are using the PSPNet one then yes.
2. They are only for your reference and are not that "plug-and-play". Look at ade_expand_inst.py for starters. This is because each source (PSPNet, deeplab, etc.) produce their output differently. We need some manual labour to "unify" the format.

**Comment by zhujiesuper** [comment]
thank you very much.
