### ISSUE TITLE
refinement is not a binary image

### ISSUE THREAD

**Issue by whitenoise-tzx** [hkchengrex/CascadePSP#60]
Hi, thank you for your amazing work!
I am implementing the model on my dataset, which is composed of cell images. The original gt has three classes, and I make the boundary class as 255 and others as 0. The output after refinement is not binary but has various pixel values.
Here are the inputs and output:
![2_gt](https://user-images.githubusercontent.com/72962618/168834407-e06c1204-b82d-4d4e-8a44-df5f094aa240.png)
![2_im](https://user-images.githubusercontent.com/72962618/168834486-0654bae7-ccfc-47f1-91ed-b6fb1cc2264b.png)
![2_seg](https://user-images.githubusercontent.com/72962618/168834537-43b93b4f-6495-47f1-b8df-56a7cb22e59a.png)
![refine](https://user-images.githubusercontent.com/72962618/168834600-cca3f405-de46-4cc9-b19e-180bbab6dcc2.png)
![2_mask](https://user-images.githubusercontent.com/72962618/168834695-5de4e75d-490d-44de-8918-349bda50b9e0.png)
The first four pictures are gt, im, seg, mask respectively, and the last one is my result after adaptive thresholding,  which gives worse metrics in terms of IoU and boundary accuracy.
Can you please check this problem and give me some possible advice?

**Comment by hkchengrex** [comment]
1. Our model is trained on object segments, not boundary segments. It might work better to fill those segments and use a morphological operator to get the boundaries as a post-processing step.
2. These cell images are very different than our training set, e.g., they don't have exact sharp boundaries and our model might not generalize.
