### ISSUE TITLE
Can this method be used as post-processing for video object segmentation? 

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/CascadePSP#61]
Hi, @hkchengrex Can this method be used as post-processing for video object segmentation? I tried it and it doesn't seem to work.

**Comment by longmalongma** [comment]
> Hi, @hkchengrex Can this method be used as post-processing for video object segmentation? I tried it and it doesn't seem to work.

Looking forward to your reply!

**Comment by hkchengrex** [comment]
It does not have any temporal consistency and does not handle motion-blurred frames well if that's what you are asking.
