### ISSUE TITLE
local step only

### ISSUE THREAD

**Issue by rondl** [hkchengrex/CascadePSP#62]
Can you provide detailed steps for using "local step only"？
I would appreciate anyone's help!

**Comment by hkchengrex** [comment]
You can just bypass these lines:
https://github.com/hkchengrex/CascadePSP/blob/3d1a645c0a65725d237756c796a25cfaaac667d0/eval_helper.py#L51-L68

**Comment by rondl** [comment]
I comment out those lines ，but it showed “Hyperparameters:  {'dir': 'testset_directory', 'model': 'model_40000', 'output': 'test_results', 'global_only': False, 'L': 900, 'stride': 450, 'clear': False, 'ade': False}
200 images found
  0% (0 of 200) |                        | Elapsed Time: 0:00:00 ETA:  --:--:--Traceback (most recent call last):
  File "eval.py", line 83, in <module>
    images = process_high_res_im(model, im, seg, para, name, aggre_device='cuda:0')
  File "/home/hndx/yhq/cascadepsp/eval_helper.py", line 82, in process_high_res_im
    r_pred_224 = (F.interpolate(pred_224, size=(h, w), mode='bilinear', align_corners=False)>0.5).float()*2-1
UnboundLocalError: local variable 'pred_224' referenced before assignment
100% (200 of 200) |######################| Elapsed Time: 0:00:00 Time:  0:00:00”

**Comment by hkchengrex** [comment]
Well you still have to define the variables... Something like `pred_224=pred_56=seg`

**Comment by rondl** [comment]
Thanks ！
