### ISSUE TITLE
Help with Colab/local setup

### ISSUE THREAD

**Issue by mohsen-azimi** [hkchengrex/CascadePSP#63]
Hi, 
After installing the package with PIP, I could not create the `refiner = refine.Refiner(device='cuda:0')  #device='cuda:0') # device can also be 'cpu' ` with Error `_pickle.UnpicklingError: invalid load key, '<'.` 
I tried PIP on the local computer, and the same error happened with Colab; I also tried to import Refiner from the cloned directory, but the same error happen. Any suggestion? Maybe, a Colab example would be great. 

Thanks!

**Comment by hkchengrex** [comment]
Might be related:
https://github.com/hkchengrex/CascadePSP/issues/53

**Comment by hkchengrex** [comment]
We have updated the package to check for errors and replaced g-drive with GitHub. Please try again after updating the package.

**Comment by mohsen-azimi** [comment]
Thanks for the updates; I downloaded the files, and it worked. I will try again with the new version.
Great work!
