### ISSUE TITLE
Tree leaves boundary refinement

### ISSUE THREAD

**Issue by lknnnli** [hkchengrex/CascadePSP#64]
Dear Author,

I'm currently looking into your work to refine my coarse mask.

when I test your pipeline, straight lines and building border are very well refined, however, when there is tree leaves, the refinement look not quite good, you can see one example result from the following figure.My purpose is to perform sky segmentation. May I know your option about this issue? Is it because generalization? Do I need to train the model again with dataset contains more tree leaves?

![DSC_9265](https://user-images.githubusercontent.com/74944568/180946832-19da302f-c705-4032-b6d7-6cc966e613bb.JPG)

Thanks a lot for your kind help
With warm regards
Kangning Li

**Comment by hkchengrex** [comment]
Might work better if you zoom into the tree region since there are different semantics in this scene. You can also try making trees the foreground.  Re-training might help but there is no guarantee that it will work for all cases.

**Comment by lknnnli** [comment]
Dear Author,
Thanks for your kind reply,
I test again following your suggestions, this time I only segment tree, and I make tree as foreground
![test](https://user-images.githubusercontent.com/74944568/181191827-b3647383-6c14-4f93-93e7-5d4398cfa63a.png)

![test](https://user-images.githubusercontent.com/74944568/181191922-5e8dd217-27e5-4c7f-a0ae-3139b803e068.png)

The image on top, is I get from Unreal Engine, tree as foreground, and the bottom one is I refine with your algorithm. It seems that CascadePSP behaves a little bit over-masking? 

I'm not sure whether this speculate is correct, do you have any suggestion?
Thanks a lot for you help
With warm regards
Kangning LI

**Comment by hkchengrex** [comment]
What's the input image/mask?

**Comment by lknnnli** [comment]
> What's the input image/mask?
![img_ComputerVision_0_0_1655866627430303800](https://user-images.githubusercontent.com/74944568/182060107-0c7bad75-949a-491f-8f99-4cae60e63eab.png)

![test](https://user-images.githubusercontent.com/74944568/182064439-b3061fc5-f05f-47ea-ba69-59b90db2d10a.png)

The top image is my input image, I got from Unreal Engine.
And The bottom image is my mask, I just Implemented a very simple segmentation tool to extract foreground tree.

Thanks a lot for you help
Best 
Kangning Li

**Comment by hkchengrex** [comment]
If I zoom into the image I see a lot of noises and artifacts. No surprise to me that it kind of failed in this case.
