### ISSUE TITLE
hashlib error

### ISSUE THREAD

**Issue by hirokic5** [hkchengrex/CascadePSP#65]
Thanks for your great repository !!!  And I also read thesis, it is very cleary written,

By the way, after this commit ( c8d658745cfe1f570712b0a8de3cc76d6c5a756e ) , there seems to be something error installing via pip. 
Maybe the error is caused by "hashlib". When remove "hashlib" in `setup.py`, the error disappeared.

**Comment by hkchengrex** [comment]
I see. `hashlib` seems to be in the standard library already. Thanks for reporting. Fixed.
