### ISSUE TITLE
Very slow prediction, high cpu /gpu usage

### ISSUE THREAD

**Issue by thebeautyofcoding** [hkchengrex/CascadePSP#67]
Hey,
Thanks for this awesome deep learning package. The results are absolutely perfect, but the prediction takes so many resources and it takes 1 minute on a high end cpu. Is this normal, or am I doing something wrong? 
Thanks ;)

**Comment by hkchengrex** [comment]
Hi, unfortunately it is expected. We did not optimize for speed in the development of this project. Using a GPU can make it faster and you might also consider acceleration techniques like mixed precision or TensoRT that are not implemented in this project.
