### ISSUE TITLE
Any low hanging fruit for generation speed improvements?

### ISSUE THREAD

**Issue by otdavies** [hkchengrex/CascadePSP#71]
Hello,

Thank you for this project and brilliant contributions to the segmentation research space.

To the point: If there are any "off the top of your head" speedups to CascadePSP that would be relatively simple.. I would be interested in attempting them. I saw one of your other issues pointed to a few examples e.g. "acceleration techniques like mixed precision or TensorRT"

Could you point toward where you would implement these changes + some baseline reasoning?

Thank you for your time and energy, it is greatly appreciated.

**Comment by hkchengrex** [comment]
https://pytorch.org/docs/stable/amp.html
https://github.com/pytorch/TensorRT

I say that because they generally improve the inference speed of neural networks.

**Comment by otdavies** [comment]
Gotcha, I'll continue to investigate those then thanks.
