### ISSUE TITLE
About the problem of dealing with redundant incomplete masks

### ISSUE THREAD

**Issue by locusbear** [hkchengrex/CascadePSP#73]
![17_mask_ori (1)](https://github.com/hkchengrex/CascadePSP/assets/46397257/b62da521-80aa-4cab-baf5-079a831f66e9)
![result (9)](https://github.com/hkchengrex/CascadePSP/assets/46397257/bba6f3fd-b40b-441b-8696-cf19d3f3df67)
It seems that CascadePSP can only remove some of the badcase pixels when the original mask predicts the presence of excess, fragmentary pixels. How should this problem be solved?

**Comment by hkchengrex** [comment]
Ultimately this is just a trained model so mistakes can happen especially when it falls outside of our domain of training data. In this particular case, some morphological erosion + dilation (i.e., opening) operations might help.

**Comment by locusbear** [comment]
> Ultimately this is just a trained model so mistakes can happen especially when it falls outside of our domain of training data. In this particular case, some morphological erosion + dilation (i.e., opening) operations might help.
I think corrosion expansion is of limited help, using the maximum connected domain determination may be more effective, and I may eventually need to retrain the model to avoid this situation, thank you very much.

**Comment by locusbear** [comment]
> Ultimately this is just a trained model so mistakes can happen especially when it falls outside of our domain of training data. In this particular case, some morphological erosion + dilation (i.e., opening) operations might help.

I think corrosion expansion is of limited help, using the maximum connected domain determination may be more effective, and I may eventually need to retrain the model to avoid this situation, thank you very much.
