### ISSUE TITLE
Query Regarding High-Resolution Image Segmentation with CascadePSP

### ISSUE THREAD

**Issue by tahsin12zaman** [hkchengrex/CascadePSP#75]
Sir,
I am writing to inquire about a specific aspect of refining segmentations using CascadePSP, as discussed in your paper. 

The demonstration on the project's GitHub page only illustrates segmentation with two colors, purple and yellow, as shown in the test.py file. Specifically, I would like to understand the process for segmenting high-resolution images, such as those presented in Figures 1, 8, 9, and 10.   Could you please provide more details on how these high-resolution segmentations are achieved?  
Thank you for your time and assistance.

Best regards,

S.M. Tahsin Zaman
Machine Learning Engineer
The KOW Company
Phone/WhatsApp: +8801521433310

**Comment by hkchengrex** [comment]
Hi. I am not sure what the question is. The colors are for visualization only and do not affect the underlying algorithm.
