### ISSUE TITLE
hello，i have a question .when you train,do you have the pspnet output(seg) before?  if not,how can you get the input seg

### ISSUE THREAD

**Issue by zhujiesuper** [hkchengrex/CascadePSP#9]

**Comment by hkchengrex** [comment]
No, we don't. The training procedure is mentioned in the paper.

**Comment by xc769458796** [comment]
Do you know how to get the input seg?

**Comment by xc769458796** [comment]
I can not find in the paper.

**Comment by hkchengrex** [comment]
It is briefly described in the third paragraph of Section 3.3. You can find the actual code in [util/boundary_modification.py ](https://github.com/hkchengrex/CascadePSP/blob/master/util/boundary_modification.py) and [util/de_transform.py](https://github.com/hkchengrex/CascadePSP/blob/master/util/de_transform.py).

**Comment by xc769458796** [comment]
I understand it now,thank you .
